export { CustomInput } from './customInput';
export { Login } from './loginPage';
export { Profile } from './profile';
// export { Registrations } from './registrations';
export { SignUpContainer } from './registrations';
export { SignUp } from './registrations';
export { Navigation } from './navigation';
export { Preloader } from './preloader';
export { TableSidebar } from './tableSidebar';
export { CustomButton } from './customButton';
export { PageError404 } from './404';
export { CreateNewPassword, ConfirmPassword, Popup } from './confirmPassword';
export { Cards } from './cards';
